# 1.0 Understand Pytorch Tensors

In [4]:
import torch

In [22]:
z = torch.zeros((5, 3), dtype=torch.int16)
o = torch.ones((3,6), dtype=torch.int16)

print(z,"\n\n", o)
print(z.dtype)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.int16) 

 tensor([[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]], dtype=torch.int16)
torch.int16


**Random Tensor**

In [39]:
torch.manual_seed(1729)
print("R1: ", torch.rand(2,2))

print("R2: ", torch.rand(2,2))

torch.manual_seed(1729)
print("R3: ", torch.rand(2,2))

R1:  tensor([[0.3126, 0.3791],
        [0.3087, 0.0736]])
R2:  tensor([[0.4216, 0.0691],
        [0.2332, 0.4047]])
R3:  tensor([[0.3126, 0.3791],
        [0.3087, 0.0736]])


In [45]:
ones = torch.ones(2,3)
twos = torch.ones(2,3)*2

print(ones)
print(twos)

threes = ones + twos
print(threes)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[3., 3., 3.],
        [3., 3., 3.]])


In [49]:
r = torch.rand(2,3) + torch.rand(3,3)
print(r)

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 0